name: GitHub pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Build
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./Resources/Public/JavaScript/
          recurse: true
          output_dir: ./Doc
          template: jsdoc3-bootstrap
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Doc
